spring.application.name=minhas-tarefas
spring.profiles.active=dev
server.servlet.context-path=/minhastarefas

app.jwt.SecretKey=ChaveSecretaSuperLongaComMaisDe32Caracteres123456789
app.jwt.ExpirationMs=28800000
