spring.application.name=minhas-tarefas
server.port=8081
server.servlet.context-path=/minhastarefas 


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3305/tarefas?serverTimezone=America/Sao_Paulo
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
